# MySQL Connect

In [ ]:
import mysql.connector

conn = mysql.connector.connect(host="localhost",user="root",password="",database="lab2")

In [ ]:
if conn.is_connected():
    print("Connected...")
else:
    print("Lost connection...")

Connected...

In [ ]:
def displayDataTables(cursor):
    # display all records
    table = cursor.fetchall()

    # describe table
    print('\n Table Description:')
    for attr in table:
	    print(attr)

In [ ]:
# create cursor instance
cursor = conn.cursor()

In [ ]:
# show databases
showDb = "show databases;"

cursor.execute(showDb)

displayDataTables(cursor)

 Table Description:
('information_schema',)
('lab2',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('sdu',)
('test',)
('testdb',)

In [ ]:
# create db
newDb = "create database testlab;"

cursor.execute(newDb)

displayDataTables(cursor)

# show databases
showDb = "show databases;"

cursor.execute(showDb)

displayDataTables(cursor)

 Table Description:

 Table Description:
('information_schema',)
('lab2',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('sdu',)
('test',)
('testdb',)
('testlab',)

In [ ]:
# drop db
newDb = "drop database testlab;"

cursor.execute(newDb)

displayDataTables(cursor)

# show databases
showDb = "show databases;"

cursor.execute(showDb)

displayDataTables(cursor)

 Table Description:

 Table Description:
('information_schema',)
('lab2',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('sdu',)
('test',)
('testdb',)

In [ ]:
# show description
showDescr = "desc customer;"

cursor.execute(showDescr)

displayDataTables(cursor)

 Table Description:
('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(80)', 'YES', '', None, '')
('credit', 'double', 'YES', '', None, '')

In [ ]:
# select customer all
customers = "select * from customer;"

cursor.execute(customers)

displayDataTables(cursor)

 Table Description:
(1, 'First Count', 10000.15)
(2, 'Second two', 9999.99)
(3, 'Third Three', 300000.15)

In [ ]:
# select customer id = 1
firstCustomer = "select * from customer where id = %s;"

cursor.execute(firstCustomer, ("1",))

displayDataTables(cursor)

 Table Description:
(1, 'First Count', 10000.15)

In [ ]:
# insert new customer
newCustomer = "insert into customer (name,credit) values ( %s, %s)"
cursor.execute(newCustomer, ("Second two", "9999.99",))

displayDataTables(cursor)

# select customer all
customers = "select * from customer;"

cursor.execute(customers)

displayDataTables(cursor)

 Table Description:

 Table Description:
(1, 'First Count', 10000.15)
(2, 'Second two', 9999.99)
(3, 'Third Three', 300000.15)
(5, 'Second two', 9999.99)

In [ ]:
# update customer
newCustomer = "update customer set name = %s where id = %s"
cursor.execute(newCustomer, ("Thanatmet T.", "0",))

displayDataTables(cursor)

# select customer all
customers = "select * from customer;"

cursor.execute(customers)

displayDataTables(cursor)

 Table Description:

 Table Description:
(1, 'First Count', 10000.15)
(2, 'Second two', 9999.99)
(3, 'Third Three', 300000.15)
(5, 'Second two', 9999.99)

In [ ]:
# delete customer
deleteCustomer = "delete from customer where id = %s"
cursor.execute(deleteCustomer, ("0",))

displayDataTables(cursor)

# select customer all
customers = "select * from customer;"

cursor.execute(customers)

displayDataTables(cursor)

 Table Description:

 Table Description:
(1, 'First Count', 10000.15)
(2, 'Second two', 9999.99)
(3, 'Third Three', 300000.15)
(5, 'Second two', 9999.99)

# Connect Mongodb

In [ ]:
import pymongo
client = pymongo.MongoClient('mongodb://localhost:27017/')

In [ ]:
db = client['customer']

In [ ]:
customer = db.employeeinformation

In [ ]:
record = {
    'name': 'First 1',
    'credit': 9999
}
customer.insert_one(record)

InsertOneResult(ObjectId('6562a8f2231409f6ca72b431'), acknowledged=True)

In [ ]:
records = [{
    'name': 'Two 2',
    'credit': 99
},
{
     'name': 'Three 3',
    'credit': 999
}]

In [ ]:
customer.insert_many(records)

InsertManyResult([ObjectId('6562a8f2231409f6ca72b432'), ObjectId('6562a8f2231409f6ca72b433')], acknowledged=True)

In [ ]:
customer.find_one()

{'_id': ObjectId('6562a8f2231409f6ca72b431'),
 'name': 'First 1',
 'credit': 9999}

In [ ]:
for record in customer.find():
    print(record)

{'_id': ObjectId('6562a8f2231409f6ca72b431'), 'name': 'First 1', 'credit': 9999}
{'_id': ObjectId('6562a8f2231409f6ca72b432'), 'name': 'Two 2', 'credit': 99}
{'_id': ObjectId('6562a8f2231409f6ca72b433'), 'name': 'Three 3', 'credit': 999}

In [ ]:
for record in customer.find({'name':'One 1'}):
    print(record)

In [ ]:
for record in customer.find({'name':{'$in':['One 1','Two 2']}}):
    print(record)

{'_id': ObjectId('6562a8f2231409f6ca72b432'), 'name': 'Two 2', 'credit': 99}

In [ ]:
for record in customer.find({'credit':{'$lt':999}}):
    print(record)

{'_id': ObjectId('6562a8f2231409f6ca72b432'), 'name': 'Two 2', 'credit': 99}